version : "3"
services : 
        arti : 
                container_name : arti
                image : mattgruter/artifactory
                volumes : 
                        - ./arti:/artifactory:rw
                ports : 
                        - "8080:8080"
